version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=TestDB
    volumes:
      - ./data:/var/lib/mysql
  app:
    container_name: test-go-hong
    build: .